jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Windows
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: build/*.geode